services:
  usbutler:
    build: usbutler
    container_name: usbutler
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/gpiochip0:/dev/gpiochip0
    volumes:
      - ./config:/app/config:ro
      - /run/udev:/run/udev:ro
      - usbutler-data:/app/data
    env_file:
      - .env
      - .env.secrets
    ports:
      - "8000:8000"

volumes:
  usbutler-data:
