services:
  usbutler:
    build: usbutler
    container_name: usbutler
    restart: always
    privileged: true
    network_mode: host
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/gpiochip0:/dev/gpiochip0
    volumes:
      - ./config:/app/config:ro
      - /run/udev:/run/udev:ro
      - usbutler-data:/app/data
    env_file:
      - .env
      - .env.secrets

volumes:
  usbutler-data:
